#!/bin/bash
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MASTER="$PROJECT_ROOT/Resources/Branding/AppIcon-master.png"
DESTINATION="$PROJECT_ROOT/Sources/OpenNoType/Resources/AppIcon.icns"
ICON_TEMP="$(mktemp -d "${TMPDIR:-/tmp}/opennotype-icon.XXXXXX")"
trap 'rm -rf "$ICON_TEMP"' EXIT
ICONSET="$ICON_TEMP/AppIcon.iconset"
mkdir -p "$ICONSET" "$(dirname "$DESTINATION")"
# Preserve the approved artwork and alpha while supplying every macOS icon size.
for size in 16 32 128 256 512; do
    /usr/bin/sips -z "$size" "$size" "$MASTER" --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
    retina_size=$((size * 2))
    /usr/bin/sips -z "$retina_size" "$retina_size" "$MASTER" --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
done
/usr/bin/iconutil -c icns "$ICONSET" -o "$ICON_TEMP/AppIcon.icns"
# Avoid touching the SwiftPM resource when the generated bytes have not changed.
if ! cmp -s "$ICON_TEMP/AppIcon.icns" "$DESTINATION"; then
    cp "$ICON_TEMP/AppIcon.icns" "$DESTINATION"
fi
printf '%s\n' "$DESTINATION"
