import Foundation

/// Decision services are independent of the speech and text-generation provider.
public enum DecisionProvider: String, Codable, CaseIterable, Identifiable, Sendable {
    case openRouter
    case typeSafe = "typesafe"

    public var id: String { rawValue }
    public var displayName: String {
        switch self { case .openRouter: "OpenRouter"; case .typeSafe: "TypeSafe" }
    }
    public var model: String {
        switch self { case .openRouter: "typesafe/jev-1.13"; case .typeSafe: "jev-1.13.0" }
    }
    public var endpoint: URL {
        switch self {
        case .openRouter: URL(string: "https://openrouter.ai/api/alpha/decisions")!
        case .typeSafe: URL(string: "https://api.typesafe.ai/v1/systemone")!
        }
    }
}

/// Runtime-only credentials. Never encoded or persisted with usage records.
public struct DecisionConfiguration: Sendable {
    public var provider: DecisionProvider
    public var apiKey: String
    public init(provider: DecisionProvider, apiKey: String) {
        self.provider = provider; self.apiKey = apiKey
    }
}

/// A caller-approved spelling candidate, never a suggestion generated by the decision model.
public struct DecisionTermCandidate: Codable, Equatable, Sendable {
    public var id: String
    public var original: String
    public var candidate: String
    public init(id: String, original: String, candidate: String) {
        self.id = id; self.original = original; self.candidate = candidate
    }
}

public struct DecisionRequest: Equatable, Sendable {
    public var transcript: String
    public var cleanedText: String
    public var termCandidates: [DecisionTermCandidate]
    public init(transcript: String, cleanedText: String, termCandidates: [DecisionTermCandidate] = []) {
        self.transcript = transcript; self.cleanedText = cleanedText; self.termCandidates = termCandidates
    }
}

public enum DecisionTermChoice: String, Codable, CaseIterable, Sendable {
    case useCandidate = "use_candidate"
    case keepOriginal = "keep_original"
    case uncertain
}

public struct DecisionTermResult: Codable, Equatable, Sendable {
    public var id: String
    public var choice: DecisionTermChoice
    public var probabilities: [DecisionTermChoice: Double]
    public var confidence: Double
    public init(id: String, choice: DecisionTermChoice, probabilities: [DecisionTermChoice: Double], confidence: Double) {
        self.id = id; self.choice = choice; self.probabilities = probabilities; self.confidence = confidence
    }
}

/// Advisory judgments only. These probabilities do not certify correctness or authorize an edit.
public struct DecisionResult: Codable, Equatable, Sendable {
    public var meaningChanged: Double
    public var contentAdded: Double
    public var contentOmitted: Double
    public var terms: [DecisionTermResult]
    public var reportedModel: String
    public var usage: ProviderUsage?
    public var maximumRiskProbability: Double { max(meaningChanged, contentAdded, contentOmitted) }
    public init(meaningChanged: Double, contentAdded: Double, contentOmitted: Double,
                terms: [DecisionTermResult] = [], reportedModel: String = DecisionClient.model,
                usage: ProviderUsage? = nil) {
        self.meaningChanged = meaningChanged; self.contentAdded = contentAdded; self.contentOmitted = contentOmitted
        self.terms = terms; self.reportedModel = reportedModel; self.usage = usage
    }
}

public protocol DecisionEvaluating: Sendable {
    func evaluate(_ input: DecisionRequest, configuration: DecisionConfiguration,
                  onUsage: (@Sendable (ProviderUsage) async -> Void)?) async throws -> DecisionResult
}

public enum DecisionError: Error, Equatable, LocalizedError, Sendable {
    case missingAPIKey, invalidInput, inputTooLarge, responseTooLarge, invalidResponse, timedOut, connectionFailed
    case httpStatus(Int)
    public var errorDescription: String? {
        switch self {
        case .missingAPIKey: return L("문장 검사에 사용할 서비스의 API 키가 필요합니다.", "Enter an API key for the text review service.")
        case .invalidInput: return L("문장 검사에 사용할 입력을 확인해 주세요.", "Check the input for text review.")
        case .inputTooLarge: return L("문장이 검사 가능한 길이를 넘었습니다.", "The text exceeds the review length limit.")
        case .responseTooLarge, .invalidResponse: return L("문장 검사 응답을 확인할 수 없습니다.", "The text review response could not be verified.")
        case .timedOut: return L("문장 검사 대기 시간이 지났습니다.", "The text review timed out.")
        case .connectionFailed: return L("문장 검사 서비스에 연결할 수 없습니다.", "Could not connect to the text review service.")
        case .httpStatus: return L("문장 검사 서비스가 요청을 처리하지 못했습니다.", "The text review service could not process the request.")
        }
    }
}
