import Foundation

/// A caller-approved spelling candidate, never a suggestion generated by the decision model.
public struct DecisionTermCandidate: Codable, Equatable, Sendable {
    public var id: String
    public var original: String
    public var candidate: String
    public init(id: String, original: String, candidate: String) {
        self.id = id; self.original = original; self.candidate = candidate
    }
}

public struct DecisionRequest: Equatable, Sendable {
    public var transcript: String
    public var cleanedText: String
    public var termCandidates: [DecisionTermCandidate]
    public init(transcript: String, cleanedText: String, termCandidates: [DecisionTermCandidate] = []) {
        self.transcript = transcript; self.cleanedText = cleanedText; self.termCandidates = termCandidates
    }
}

public enum DecisionTermChoice: String, Codable, CaseIterable, Sendable {
    case useCandidate = "use_candidate"
    case keepOriginal = "keep_original"
    case uncertain
}

public struct DecisionTermResult: Codable, Equatable, Sendable {
    public var id: String
    public var choice: DecisionTermChoice
    public var probabilities: [DecisionTermChoice: Double]
    public var confidence: Double
    public init(id: String, choice: DecisionTermChoice, probabilities: [DecisionTermChoice: Double], confidence: Double) {
        self.id = id; self.choice = choice; self.probabilities = probabilities; self.confidence = confidence
    }
}

/// Advisory judgments only. These probabilities do not certify correctness or authorize an edit.
public struct DecisionResult: Codable, Equatable, Sendable {
    public var meaningChanged: Double
    public var contentAdded: Double
    public var contentOmitted: Double
    public var terms: [DecisionTermResult]
    public var reportedModel: String
    public var usage: ProviderUsage?
    public var maximumRiskProbability: Double { max(meaningChanged, contentAdded, contentOmitted) }
    public init(meaningChanged: Double, contentAdded: Double, contentOmitted: Double,
                terms: [DecisionTermResult] = [], reportedModel: String = DecisionClient.model,
                usage: ProviderUsage? = nil) {
        self.meaningChanged = meaningChanged; self.contentAdded = contentAdded; self.contentOmitted = contentOmitted
        self.terms = terms; self.reportedModel = reportedModel; self.usage = usage
    }
}

public protocol DecisionEvaluating: Sendable {
    func evaluate(_ input: DecisionRequest, apiKey: String,
                  onUsage: (@Sendable (ProviderUsage) async -> Void)?) async throws -> DecisionResult
}

public enum DecisionError: Error, Equatable, LocalizedError, Sendable {
    case missingAPIKey, invalidInput, inputTooLarge, responseTooLarge, invalidResponse, timedOut, connectionFailed
    case httpStatus(Int)
    public var errorDescription: String? {
        switch self {
        case .missingAPIKey: return "문장 검사에 사용할 OpenRouter 키가 필요합니다."
        case .invalidInput: return "문장 검사에 사용할 입력을 확인해 주세요."
        case .inputTooLarge: return "문장이 검사 가능한 길이를 넘었습니다."
        case .responseTooLarge, .invalidResponse: return "문장 검사 응답을 확인할 수 없습니다."
        case .timedOut: return "문장 검사 대기 시간이 지났습니다."
        case .connectionFailed: return "문장 검사 서비스에 연결할 수 없습니다."
        case .httpStatus: return "문장 검사 서비스가 요청을 처리하지 못했습니다."
        }
    }
}
