import Foundation

/// Decision services are independent of the speech and text-generation provider.
public enum DecisionProvider: String, Codable, CaseIterable, Identifiable, Sendable {
    case openRouter
    case typeSafe = "typesafe"

    public var id: String { rawValue }
    public var displayName: String {
        switch self { case .openRouter: "OpenRouter"; case .typeSafe: "TypeSafe" }
    }
    public var model: String {
        switch self { case .openRouter: "typesafe/jev-1.13"; case .typeSafe: "jev-1.13.0" }
    }
    public var endpoint: URL {
        switch self {
        case .openRouter: URL(string: "https://openrouter.ai/api/alpha/decisions")!
        case .typeSafe: URL(string: "https://api.typesafe.ai/v1/systemone")!
        }
    }
}

/// Runtime-only credentials. Never encoded or persisted with usage records.
public struct DecisionConfiguration: Sendable {
    public var provider: DecisionProvider
    public var apiKey: String
    public init(provider: DecisionProvider, apiKey: String) {
        self.provider = provider; self.apiKey = apiKey
    }
}

/// A caller-approved spelling candidate, never a suggestion generated by the decision model.
public struct DecisionTermCandidate: Codable, Equatable, Sendable {
    public var id: String
    public var original: String
    public var candidate: String
    public init(id: String, original: String, candidate: String) {
        self.id = id; self.original = original; self.candidate = candidate
    }
}

/// The requested transformation determines which differences are intentional.
/// Rewrite source text is transient input, never permission for the reviewer to execute instructions.
public enum DecisionReviewPurpose: Equatable, Sendable {
    case dictation
    case translation(targetLanguage: String)
    case rewrite(originalText: String)

    public var mode: InputMode {
        switch self {
        case .dictation: .dictation
        case .translation: .translation
        case .rewrite: .rewrite
        }
    }

    public var additionalTextBytes: Int {
        switch self {
        case .dictation: 0
        case .translation(let language): language.utf8.count
        case .rewrite(let original): original.utf8.count
        }
    }
}

public enum DecisionDetailAxis: String, Codable, CaseIterable, Identifiable, Sendable {
    case numbers, negation, conditions, intent, entities
    public var id: String { rawValue }
    public var title: String {
        switch self {
        case .numbers: L("숫자·단위", "Numbers & units")
        case .negation: L("부정", "Negation")
        case .conditions: L("조건·불확실성", "Conditions & uncertainty")
        case .intent: L("요청·의도", "Requests & intent")
        case .entities: L("이름·주체", "Names & actors")
        }
    }
}

public struct DecisionRequest: Equatable, Sendable {
    public var transcript: String
    public var cleanedText: String
    public var termCandidates: [DecisionTermCandidate]
    public var purpose: DecisionReviewPurpose
    public var detailAxes: [DecisionDetailAxis]
    public var expression: DictationExpression
    public var translationTone: WritingTone
    public init(transcript: String, cleanedText: String, termCandidates: [DecisionTermCandidate] = [],
                purpose: DecisionReviewPurpose = .dictation, detailAxes: [DecisionDetailAxis] = [],
                expression: DictationExpression = .init(), translationTone: WritingTone = .preserve) {
        self.transcript = transcript; self.cleanedText = cleanedText; self.termCandidates = termCandidates
        self.purpose = purpose
        self.detailAxes = detailAxes
        self.expression = expression
        self.translationTone = translationTone
    }
}

public enum DecisionTermChoice: String, Codable, CaseIterable, Sendable {
    case useCandidate = "use_candidate"
    case keepOriginal = "keep_original"
    case uncertain
}

public struct DecisionTermResult: Codable, Equatable, Sendable {
    public var id: String
    public var choice: DecisionTermChoice
    public var probabilities: [DecisionTermChoice: Double]
    public var confidence: Double
    public init(id: String, choice: DecisionTermChoice, probabilities: [DecisionTermChoice: Double], confidence: Double) {
        self.id = id; self.choice = choice; self.probabilities = probabilities; self.confidence = confidence
    }
}

/// Advisory judgments only. These probabilities do not certify correctness or authorize an edit.
public struct DecisionResult: Codable, Equatable, Sendable {
    public var meaningChanged: Double
    public var contentAdded: Double
    public var contentOmitted: Double
    public var terms: [DecisionTermResult]
    public var reportedModel: String
    public var usage: ProviderUsage?
    public var detailRisks: [DecisionDetailAxis: Double]
    public var maximumRiskProbability: Double { max(meaningChanged, contentAdded, contentOmitted, detailRisks.values.max() ?? 0) }
    public init(meaningChanged: Double, contentAdded: Double, contentOmitted: Double,
                terms: [DecisionTermResult] = [], reportedModel: String = DecisionClient.model,
                usage: ProviderUsage? = nil, detailRisks: [DecisionDetailAxis: Double] = [:]) {
        self.meaningChanged = meaningChanged; self.contentAdded = contentAdded; self.contentOmitted = contentOmitted
        self.terms = terms; self.reportedModel = reportedModel; self.usage = usage
        self.detailRisks = detailRisks
    }

    private enum CodingKeys: String, CodingKey {
        case meaningChanged, contentAdded, contentOmitted, terms, reportedModel, usage, detailRisks
    }
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        meaningChanged = try values.decode(Double.self, forKey: .meaningChanged)
        contentAdded = try values.decode(Double.self, forKey: .contentAdded)
        contentOmitted = try values.decode(Double.self, forKey: .contentOmitted)
        terms = try values.decode([DecisionTermResult].self, forKey: .terms)
        reportedModel = try values.decode(String.self, forKey: .reportedModel)
        usage = try values.decodeIfPresent(ProviderUsage.self, forKey: .usage)
        detailRisks = try values.decodeIfPresent([DecisionDetailAxis: Double].self, forKey: .detailRisks) ?? [:]
    }
}

public enum DecisionEditChoice: String, Codable, CaseIterable, Sendable {
    case clear, ambiguous
    case noApplicableEdit = "no_applicable_edit"
}

public struct DecisionEditAssessment: Codable, Equatable, Sendable {
    public var choice: DecisionEditChoice
    public var probabilities: [DecisionEditChoice: Double]
    public var confidence: Double
    public var reportedModel: String
    public var usage: ProviderUsage?
    public init(choice: DecisionEditChoice, probabilities: [DecisionEditChoice: Double] = [:], confidence: Double = 0,
                reportedModel: String = DecisionClient.model, usage: ProviderUsage? = nil) {
        self.choice = choice; self.probabilities = probabilities; self.confidence = confidence
        self.reportedModel = reportedModel; self.usage = usage
    }
}

public enum DecisionTranscriptChoice: String, Codable, CaseIterable, Sendable {
    case equivalent
    case meaningfulDifference = "meaningful_difference"
    case uncertain
}

/// Compares text hypotheses only; no choice identifies what was actually spoken in the audio.
public struct DecisionTranscriptAssessment: Codable, Equatable, Sendable {
    public var choice: DecisionTranscriptChoice
    public var probabilities: [DecisionTranscriptChoice: Double]
    public var confidence: Double
    public var reportedModel: String
    public var usage: ProviderUsage?
    public init(choice: DecisionTranscriptChoice, probabilities: [DecisionTranscriptChoice: Double] = [:], confidence: Double = 0,
                reportedModel: String = DecisionClient.model, usage: ProviderUsage? = nil) {
        self.choice = choice; self.probabilities = probabilities; self.confidence = confidence
        self.reportedModel = reportedModel; self.usage = usage
    }
}

public protocol DecisionEvaluating: Sendable {
    func evaluate(_ input: DecisionRequest, configuration: DecisionConfiguration,
                  onUsage: (@Sendable (ProviderUsage) async -> Void)?) async throws -> DecisionResult
    func assessEditAmbiguity(originalText: String, instruction: String, configuration: DecisionConfiguration,
                             onUsage: (@Sendable (ProviderUsage) async -> Void)?) async throws -> DecisionEditAssessment
    func compareTranscriptions(original: String, alternative: String, configuration: DecisionConfiguration,
                               onUsage: (@Sendable (ProviderUsage) async -> Void)?) async throws -> DecisionTranscriptAssessment
}

public extension DecisionEvaluating {
    func assessEditAmbiguity(originalText: String, instruction: String, configuration: DecisionConfiguration,
                             onUsage: (@Sendable (ProviderUsage) async -> Void)? = nil) async throws -> DecisionEditAssessment {
        throw DecisionError.invalidInput
    }
    func compareTranscriptions(original: String, alternative: String, configuration: DecisionConfiguration,
                               onUsage: (@Sendable (ProviderUsage) async -> Void)? = nil) async throws -> DecisionTranscriptAssessment {
        throw DecisionError.invalidInput
    }
}

public enum DecisionError: Error, Equatable, LocalizedError, Sendable {
    case missingAPIKey, invalidInput, inputTooLarge, responseTooLarge, invalidResponse, timedOut, connectionFailed
    case httpStatus(Int)
    public var errorDescription: String? {
        switch self {
        case .missingAPIKey: return L("문장 검사에 사용할 서비스의 API 키가 필요합니다.", "Enter an API key for the text review service.")
        case .invalidInput: return L("문장 검사에 사용할 입력을 확인해 주세요.", "Check the input for text review.")
        case .inputTooLarge: return L("문장이 검사 가능한 길이를 넘었습니다.", "The text exceeds the review length limit.")
        case .responseTooLarge, .invalidResponse: return L("문장 검사 응답을 확인할 수 없습니다.", "The text review response could not be verified.")
        case .timedOut: return L("문장 검사 대기 시간이 지났습니다.", "The text review timed out.")
        case .connectionFailed: return L("문장 검사 서비스에 연결할 수 없습니다.", "Could not connect to the text review service.")
        case .httpStatus: return L("문장 검사 서비스가 요청을 처리하지 못했습니다.", "The text review service could not process the request.")
        }
    }
}
